import { SCHOOL_NAME, SCHOOL_MOTTO, SCHOOL_APPROVAL_NO, SCHOOL_PHONES } from "@/assets/logo";

/** Naira formatter used everywhere money is shown. */
export const naira = (value: number | string | null | undefined) =>
  `₦${Number(value || 0).toLocaleString("en-NG", { maximumFractionDigits: 2 })}`;

export type InvoiceStatus = "unpaid" | "part_paid" | "paid";

export const invoiceStatusLabel = (status?: string | null) =>
  status === "paid" ? "Paid in full" : status === "part_paid" ? "Part payment" : "Unpaid";

export const invoiceStatusTone = (status?: string | null) =>
  status === "paid"
    ? "bg-success/10 text-success border-success/20"
    : status === "part_paid"
      ? "bg-warning/10 text-warning border-warning/20"
      : "bg-destructive/10 text-destructive border-destructive/20";

export const balanceOf = (invoice: { total?: number | null; amount_paid?: number | null } | null | undefined) =>
  Number(invoice?.total || 0) - Number(invoice?.amount_paid || 0);

export const isOverdue = (invoice: { due_date?: string | null; total?: number | null; amount_paid?: number | null }) =>
  Boolean(invoice.due_date) && balanceOf(invoice) > 0 && new Date(invoice.due_date as string) < new Date();

/** Replaces {{placeholder}} tokens in a message template. */
export const renderTemplate = (body: string, values: Record<string, string>) =>
  body.replace(/\{\{\s*([a-z_]+)\s*\}\}/gi, (_m, key: string) => values[key.toLowerCase()] ?? `{{${key}}}`);

export const TEMPLATE_PLACEHOLDERS = [
  "parent_name",
  "student_name",
  "class_name",
  "term",
  "balance",
  "due_date",
  "date",
  "title",
  "body",
];

/** Opens a clean, branded print window for a document node. */
export const printDocument = (elementId: string, documentTitle: string) => {
  const node = document.getElementById(elementId);
  if (!node) return;
  const win = window.open("", "_blank", "width=900,height=1000");
  if (!win) return;
  win.document.write(`<!doctype html><html><head><title>${documentTitle}</title>
    <style>
      *{box-sizing:border-box;}
      body{font-family:'Plus Jakarta Sans',system-ui,-apple-system,sans-serif;color:#0f172a;margin:32px;}
      .doc-head{text-align:center;border-bottom:3px double #0f2d5c;padding-bottom:12px;margin-bottom:20px;}
      .doc-head h1{margin:0;font-size:20px;color:#0f2d5c;letter-spacing:.02em;}
      .doc-head p{margin:2px 0;font-size:11px;color:#475569;}
      table{width:100%;border-collapse:collapse;margin-top:12px;font-size:13px;}
      th,td{padding:8px 10px;border-bottom:1px solid #e2e8f0;text-align:left;}
      th{background:#f1f5f9;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#475569;}
      td.num,th.num{text-align:right;}
      .totals td{font-weight:700;}
      .meta{display:flex;justify-content:space-between;font-size:12px;gap:24px;flex-wrap:wrap;}
      .meta div{line-height:1.7;}
      .stamp{margin-top:28px;font-size:11px;color:#475569;display:flex;justify-content:space-between;}
      .foot{margin-top:36px;text-align:center;font-size:10px;color:#64748b;border-top:1px solid #e2e8f0;padding-top:10px;}
      .no-print{display:none !important;}
    </style></head><body>
    <div class="doc-head">
      <h1>${SCHOOL_NAME.toUpperCase()}</h1>
      <p>${SCHOOL_MOTTO} &middot; ${SCHOOL_APPROVAL_NO}</p>
      <p>${SCHOOL_PHONES.join(" , ")}</p>
    </div>
    ${node.innerHTML}
    <div class="foot">This document was generated by the school office. Kindly retain it for your records.</div>
    </body></html>`);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 250);
};
