// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's profile and role in the school portal.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: pErr }, { data: role, error: rErr }] = await Promise.all([
      supabase.from("profiles").select("*").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId).maybeSingle()
    ]);
    const error = pErr ?? rErr;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = { email: ctx.getUserEmail(), profile, role: role?.role ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-students.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_students_default = defineTool2({
  name: "list_students",
  title: "List students",
  description: "List students visible to the signed-in user, optionally filtered by name/admission number or class.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Match student name or admission number."),
    class_id: z.string().uuid().optional().describe("Restrict results to one class."),
    limit: z.number().int().min(1).max(100).default(25).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, class_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("students").select("id, student_id, first_name, last_name, class_id, status, section, guardian_name, guardian_phone").order("last_name", { ascending: true }).limit(limit ?? 25);
    if (class_id) query = query.eq("class_id", class_id);
    if (search) {
      const s = search.replace(/[%,]/g, " ");
      query = query.or(`first_name.ilike.%${s}%,last_name.ilike.%${s}%,student_id.ilike.%${s}%`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { students: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-student-record.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_student_record_default = defineTool3({
  name: "get_student_record",
  title: "Get student record",
  description: "Fetch one student's profile with their recent grades and attendance summary, by student UUID or admission number.",
  inputSchema: {
    student: z2.string().trim().min(1).describe("Student UUID or admission number (e.g. M/P01/06).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ student }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(student);
    const { data: row, error } = await supabase.from("students").select("*").eq(isUuid ? "id" : "student_id", student).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!row) return { content: [{ type: "text", text: "No student found or not visible to you." }], isError: true };
    const [{ data: grades }, { data: attendance }] = await Promise.all([
      supabase.from("grades").select("*").eq("student_id", row.id).limit(50),
      supabase.from("attendance").select("status, date").eq("student_id", row.id).order("date", { ascending: false }).limit(60)
    ]);
    const result = {
      student: { ...row, parent_code: void 0 },
      grades: grades ?? [],
      recent_attendance: attendance ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-classes.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_classes_default = defineTool4({
  name: "list_classes",
  title: "List classes",
  description: "List the school's classes (Kindergarten through Grade 6) with arm, level and room.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("classes").select("id, name, arm, level, grade_level, room, capacity").order("grade_level", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { classes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-announcements.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_announcements_default = defineTool5({
  name: "list_announcements",
  title: "List announcements",
  description: "List published school announcements visible to the signed-in user.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("announcements").select("id, title, body, priority, target_role, created_at").eq("is_published", true).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { announcements: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "weqzvfpzuybyuvruumae";
var mcp_default = defineMcp({
  name: "image-makers-school-mangementsystem",
  title: "Image Makers School mangementsystem",
  version: "0.1.0",
  instructions: "Tools for the Imagemakers Nursery and Primary School management portal. Use `get_my_profile` to see who you are acting as, `list_classes` and `list_students` to browse the roll, `get_student_record` for one pupil's grades and attendance, and `list_announcements` for school notices. All data is scoped by the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_classes_default,
    list_students_default,
    get_student_record_default,
    list_announcements_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
