// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weqzvfpzuybyuvruumae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlcXp2ZnB6dXlieXV2cnV1bWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4NjE2NTYsImV4cCI6MjEwMTQzNzY1Nn0.v2O9FOtlO5naESuOPsVU-u2Q8ha7SY2IS97vblmD2Cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});